version: '3.8'

services:
  db:
    image: postgres:16
    container_name: cesizen_db
    restart: always
    environment:
      POSTGRES_DB: app
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  api:
    build:
      context: ./apps/api
    container_name: cesizen_api
    depends_on:
      - db
    working_dir: /app
    volumes:
      - ./apps/api:/app
    ports:
      - "8080:8000"
    environment:
      DATABASE_URL: "pgsql://postgres:postgres@db:5432/app?serverVersion=16&charset=utf8"
      MAILER_DSN: "smtp://maildev:1025"
    command: ["php", "-S", "0.0.0.0:8000", "-t", "public"]

  maildev:
    image: maildev/maildev
    container_name: cesizen_maildev
    ports:
      - "1080:1080" # interface web
      - "1025:1025" # port SMTP

volumes:
  postgres_data:
